Chore/neo blog
mahdisolgi1/neo-blog pull request #36
Opened 2024-11-29 07:04 UTC by mahdisolgi1

### PR Summary:
This pull request includes a few of updates and enhancements to various components within the project.

### Changes Made:

#### General Improvements:

- Removed unnecessary stackdump.exe file.

- Added a README file with a project description and setup instructions.

- Installed and set up Storybook for UI component development.

- Added the Button component to Storybook for easier visual testing.

2024-11-30 15:44 UTC, amirrezaDev1378 requested changes

2024-11-30 15:44 UTC, amirrezaDev1378 commented on frontend/src/stories/Button.stories.ts
remove comments and rename the title

2024-11-30 15:44 UTC, amirrezaDev1378 commented on frontend/src/stories/Configure.mdx
remove this

2024-11-30 15:44 UTC, amirrezaDev1378 commented on frontend/src/stories/Header.stories.ts
remove comment and rename title

2024-11-30 15:44 UTC, amirrezaDev1378 commented on frontend/src/stories/Page.tsx
remove this

2024-11-30 15:44 UTC, amirrezaDev1378 commented on frontend/src/stories/assets/accessibility.png
remove

2024-11-30 15:44 UTC, amirrezaDev1378 commented on frontend/src/stories/assets/accessibility.svg
remove all unused asstes ...

2024-11-30 15:44 UTC, amirrezaDev1378 commented on package.json
why did you add this ? either remove it or merge it

2024-12-02 11:56 UTC, mahdisolgi1 commented
I removed stories folder because it wasn't used

2024-12-02 12:30 UTC, amirrezaDev1378 approved these changes

2024-12-02 12:31 UTC, merged